version: 2

models:
  - name: occurrences
    description: >
      This model standardizes data from GBIF and OBIS datasets, merges them, and filters the occurrences
      based on a reference species list from the WoRMS (World Register of Marine Species) table.
      The data is partitioned by event_date (month granularity) and clustered by geography.
    columns:
      - name: event_date
        description: >
          The date of the event when the species occurrence was recorded. This is standardized
          across GBIF and OBIS datasets and used as a partitioning field.
        data_tests:
          - not_null

      - name: species
        description: >
          The scientific name of the species observed. It is standardized and validated against
          the WoRMS scientificName field.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.worms_table
              field: scientificName

      - name: individual_count
        description: >
          The count of individuals observed during the event. This field is directly taken from
          the GBIF and OBIS data sources and standardized for consistent aggregation.
        data_tests:
          - not_null
      - name: geography
        description: >
          The geographic location where the event occurred. It is a standardized field from
          the GBIF and OBIS datasets and used as a clustering field.
        data_tests:
          - not_null

      - name: source
        description: >
          The source of the observation data, either 'GBIF' or 'OBIS', to track data lineage and provenance.
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 'GBIF'
                - 'OBIS'

  - name: clustered_occurrences
    description: >
      This model clusters the standardized occurrences data by species for optimized query performance.
      It references the `occurences` model, which standardizes data from GBIF and OBIS datasets
      and validates species against the WoRMS reference table.
    columns:
      - name: event_date
        description: >
          The date of the event when the species occurrence was recorded. This is inherited from
          the `occurences` model and ensures consistent data formatting across downstream models.
        data_tests:
          - not_null

      - name: species
        description: >
          The scientific name of the species observed. This field is used as the clustering key in this model
          to optimize queries involving species-level analysis.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.worms_table
              field: scientificName

      - name: individual_count
        description: >
          The count of individuals observed during the event. This field is directly inherited
          from the `occurences` model and ensures consistent aggregation and reporting.
        data_tests:
          - not_null

      - name: geography
        description: >
          The geographic location where the event occurred. This is inherited from the `occurences` model
          for consistent geospatial analysis in downstream applications.
        data_tests:
          - not_null
      - name: source
        description: >
          The source of the observation data, either 'GBIF' or 'OBIS', as inherited from the `occurences` model.
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 'GBIF'
                - 'OBIS'