version: 2

models:
  - name: occurrences
    description: >
      Unified occurrence table merging GBIF and OBIS data. Only species validated against the
      WoRMS taxonomy are retained (INNER JOIN). Partitioned by event_date (month) and clustered
      by geography for efficient spatial and temporal queries.
    columns:
      - name: event_date
        description: Timestamp of the observation, used as the partition key (month granularity).
        data_tests:
          - not_null

      - name: species
        description: WoRMS-validated scientific name of the observed species.
        data_tests:
          - not_null
          - relationships:
              to: source('marine_data', 'worms_table')
              field: scientificName

      - name: individual_count
        description: Number of individuals observed (defaults to 1 when null in source).
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the observation, used as the clustering key.
        data_tests:
          - not_null

      - name: source
        description: Data provenance tag indicating which upstream dataset the row came from.
        data_tests:
          - not_null
          - accepted_values:
              values: ['GBIF', 'OBIS']

  - name: clustered_occurrences
    description: >
      Re-clustered copy of occurrences with species as the clustering key. Optimises
      species-level lookups used by the search app and downstream aggregations.
    columns:
      - name: event_date
        description: Timestamp of the observation.
        data_tests:
          - not_null

      - name: species
        description: WoRMS-validated scientific name, used as the clustering key.
        data_tests:
          - not_null

      - name: individual_count
        description: Number of individuals observed.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the observation.
        data_tests:
          - not_null

      - name: source
        description: Data provenance tag (GBIF or OBIS).
        data_tests:
          - not_null
          - accepted_values:
              values: ['GBIF', 'OBIS']

  - name: species
    description: >
      Deduplicated species reference table built from clustered_occurrences. Flags each species
      as endangered (IUCN Red List), invasive (GISD), or normal via LEFT JOINs. Enrichment
      data (common_name, description, image_url) lives in the separate species_enrichment
      table managed by the enrichment pipeline.
    columns:
      - name: species
        description: Unique scientific name. Primary key for this table.
        data_tests:
          - not_null
          - unique

      - name: is_endangered
        description: TRUE if the species appears on the IUCN Red List.
        data_tests:
          - not_null
          - accepted_values:
              values: [true, false]
              quote: false

      - name: is_invasive
        description: TRUE if the species appears in the Global Invasive Species Database.
        data_tests:
          - not_null
          - accepted_values:
              values: [true, false]
              quote: false

      - name: species_type
        description: >
          Classification label derived from conservation status. Endangered takes priority
          over invasive if a species appears in both lists.
        data_tests:
          - not_null
          - accepted_values:
              values: ['endangered', 'invasive', 'normal']
