version: 2

models:
  - name: near_dive_site_occurrences
    description: >
      Joins every species occurrence to its nearest dive site within a configurable radius
      (PROXIMITY_METERS env var). Uses a CROSS JOIN filtered by ST_DWithin, then ranks by
      distance and keeps only the closest site (proximity_rank = 1). In dev mode, a 5%
      hash-based species subsample reduces the cross-join cost.
    columns:
      - name: dive_site
        description: Name of the nearest dive site within the proximity threshold.
        data_tests:
          - not_null
          - relationships:
              to: ref('divesites')
              field: title

      - name: event_date
        description: Timestamp of the observation.
        data_tests:
          - not_null

      - name: species
        description: WoRMS-validated scientific name of the observed species.
        data_tests:
          - not_null
          - relationships:
              to: source('marine_data', 'worms_table')
              field: scientificName

      - name: individual_count
        description: Number of individuals observed.
        data_tests:
          - not_null

      - name: distance_to_dive_site
        description: Distance in metres between the occurrence and the matched dive site.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the occurrence.
        data_tests:
          - not_null

      - name: source
        description: Data provenance tag (GBIF or OBIS).
        data_tests:
          - not_null
          - accepted_values:
              values: ['GBIF', 'OBIS']

      - name: proximity_rank
        description: Always 1 in this table since only the closest dive site is retained.
        data_tests:
          - not_null
          - accepted_values:
              values: [1]
              quote: false

  - name: monthly_species_occurrences
    description: >
      Monthly aggregation of species sightings per dive site. Joins counts back to the
      divesites table for geography metadata. Used by the Looker Studio dashboard for
      temporal trend charts.
    columns:
      - name: dive_site
        description: Name of the dive site.
        data_tests:
          - not_null

      - name: species
        description: Scientific name of the species.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the dive site.
        data_tests:
          - not_null

      - name: month
        description: Three-letter month abbreviation (e.g. Jan, Feb).
        data_tests:
          - not_null
          - accepted_values:
              values: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

      - name: event_date
        description: Observation date used for the aggregation.
        data_tests:
          - not_null

      - name: sighting_count
        description: Number of occurrences for this species at this site on this date.
        data_tests:
          - not_null

  - name: divesite_species_frequency
    description: >
      Species ranked by total sighting frequency at each dive site. Frequency rank 1
      indicates the most commonly observed species. Intermediate table feeding the
      denormalized UI models.
    columns:
      - name: dive_site
        description: Name of the dive site.
        data_tests:
          - not_null

      - name: species
        description: Scientific name of the species.
        data_tests:
          - not_null

      - name: sighting_count
        description: Total number of occurrences for this species at this dive site.
        data_tests:
          - not_null

      - name: frequency_rank
        description: Rank by sighting count within the dive site (1 = most frequent).
        data_tests:
          - not_null

  - name: species_divesite_summary
    description: >
      Denormalized table for species search → dive site distribution map.
      Clustered by species for fast single-species lookups. Each row is a
      (species, dive_site) pair with species metadata and dive site coordinates.
    columns:
      - name: species
        description: Scientific name (cluster key). Use for WHERE species = 'X' queries.
        data_tests:
          - not_null

      - name: common_name
        description: English common name from GBIF (nullable — not all species have one).

      - name: image_url
        description: Wikipedia/Wikidata image URL (nullable).

      - name: is_endangered
        description: TRUE if species is on the IUCN Red List.
        data_tests:
          - not_null

      - name: is_invasive
        description: TRUE if species is in the Global Invasive Species Database.
        data_tests:
          - not_null

      - name: species_type
        description: Conservation status label for UI badges.
        data_tests:
          - not_null
          - accepted_values:
              values: ['endangered', 'invasive', 'normal']

      - name: dive_site
        description: Name of the dive site where this species has been observed.
        data_tests:
          - not_null

      - name: dive_site_latitude
        description: Latitude of the dive site for map marker placement.
        data_tests:
          - not_null

      - name: dive_site_longitude
        description: Longitude of the dive site for map marker placement.
        data_tests:
          - not_null

      - name: sighting_count
        description: Total number of occurrences for this species at this dive site.
        data_tests:
          - not_null

      - name: frequency_rank
        description: Rank of this species at this dive site (1 = most common).
        data_tests:
          - not_null

  - name: divesite_species_detail
    description: >
      Denormalized table for dive site explorer → species panel.
      Clustered by dive_site for fast single-site lookups. Each row is a
      (dive_site, species) pair with full species metadata for rendering cards.
    columns:
      - name: dive_site
        description: Dive site name (cluster key). Use for WHERE dive_site = 'X' queries.
        data_tests:
          - not_null

      - name: dive_site_latitude
        description: Latitude for map rendering.
        data_tests:
          - not_null

      - name: dive_site_longitude
        description: Longitude for map rendering.
        data_tests:
          - not_null

      - name: species
        description: Scientific name of the species.
        data_tests:
          - not_null

      - name: common_name
        description: English common name (nullable).

      - name: description
        description: Wikipedia extract for species info panel (nullable).

      - name: image_url
        description: Species image URL for card rendering (nullable).

      - name: is_endangered
        description: IUCN Red List flag for badge rendering.
        data_tests:
          - not_null

      - name: is_invasive
        description: GISD flag for badge rendering.
        data_tests:
          - not_null

      - name: species_type
        description: Conservation status label.
        data_tests:
          - not_null
          - accepted_values:
              values: ['endangered', 'invasive', 'normal']

      - name: sighting_count
        description: Total sightings at this dive site.
        data_tests:
          - not_null

      - name: frequency_rank
        description: Species popularity rank at this site (1 = most frequent).
        data_tests:
          - not_null

  - name: divesite_summary
    description: >
      Lightweight overview table for the dive site map. One row per dive site with
      species counts and coordinates. Small enough (~3,400 rows) to load entirely
      on app initialization for map marker rendering.
    columns:
      - name: dive_site
        description: Dive site name (not globally unique — some sites share names).
        data_tests:
          - not_null

      - name: latitude
        description: Latitude for map marker.
        data_tests:
          - not_null

      - name: longitude
        description: Longitude for map marker.
        data_tests:
          - not_null

      - name: total_species
        description: Number of distinct species observed near this dive site.
        data_tests:
          - not_null

      - name: total_sightings
        description: Total occurrence count across all species.
        data_tests:
          - not_null

      - name: endangered_count
        description: Number of IUCN Red List species at this site.
        data_tests:
          - not_null

      - name: invasive_count
        description: Number of invasive species at this site.
        data_tests:
          - not_null

exposures:
  - name: divesite_species_dashboard
    label: Divesite Species Dashboard
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/s/ipP867eyaQw
    depends_on:
      - ref('divesite_species_frequency')
      - ref('monthly_species_occurrences')
      - ref('species')
    owner:
      email: aleksandr.kolmakov@pm.me

  - name: marine_species_search
    label: Marine Species Search App
    type: application
    maturity: medium
    url: https://marine-species-search.streamlit.app/
    depends_on:
      - ref('species')
      - ref('species_divesite_summary')
      - ref('divesite_species_detail')
      - ref('divesite_summary')
    owner:
      email: aleksandr.kolmakov@pm.me
