version: 2

models:
  - name: near_dive_site_occurrences
    description: >
      Joins every species occurrence to its nearest dive site within a configurable radius
      (PROXIMITY_METERS env var). Uses a CROSS JOIN filtered by ST_DWithin, then ranks by
      distance and keeps only the closest site (proximity_rank = 1). In dev mode, a 5%
      hash-based species subsample reduces the cross-join cost.
    columns:
      - name: dive_site
        description: Name of the nearest dive site within the proximity threshold.
        data_tests:
          - not_null
          - relationships:
              to: ref('divesites')
              field: title

      - name: event_date
        description: Timestamp of the observation.
        data_tests:
          - not_null

      - name: species
        description: WoRMS-validated scientific name of the observed species.
        data_tests:
          - not_null
          - relationships:
              to: source('marine_data', 'worms_table')
              field: scientificName

      - name: individual_count
        description: Number of individuals observed.
        data_tests:
          - not_null

      - name: distance_to_dive_site
        description: Distance in metres between the occurrence and the matched dive site.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the occurrence.
        data_tests:
          - not_null

      - name: source
        description: Data provenance tag (GBIF or OBIS).
        data_tests:
          - not_null
          - accepted_values:
              values: ['GBIF', 'OBIS']

      - name: proximity_rank
        description: Always 1 in this table since only the closest dive site is retained.
        data_tests:
          - not_null
          - accepted_values:
              values: [1]
              quote: false

  - name: monthly_species_occurrences
    description: >
      Monthly aggregation of species sightings per dive site. Joins counts back to the
      divesites table for geography metadata. Used by the Looker Studio dashboard for
      temporal trend charts.
    columns:
      - name: dive_site
        description: Name of the dive site.
        data_tests:
          - not_null

      - name: species
        description: Scientific name of the species.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the dive site.
        data_tests:
          - not_null

      - name: month
        description: Three-letter month abbreviation (e.g. Jan, Feb).
        data_tests:
          - not_null
          - accepted_values:
              values: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

      - name: event_date
        description: Observation date used for the aggregation.
        data_tests:
          - not_null

      - name: sighting_count
        description: Number of occurrences for this species at this site on this date.
        data_tests:
          - not_null

  - name: divesite_species_frequency
    description: >
      Species ranked by total sighting frequency at each dive site. Frequency rank 1
      indicates the most commonly observed species. Used by the Looker Studio dashboard
      and Streamlit app for "what lives here" queries.
    columns:
      - name: dive_site
        description: Name of the dive site.
        data_tests:
          - not_null

      - name: species
        description: Scientific name of the species.
        data_tests:
          - not_null

      - name: sighting_count
        description: Total number of occurrences for this species at this dive site.
        data_tests:
          - not_null

      - name: frequency_rank
        description: Rank by sighting count within the dive site (1 = most frequent).
        data_tests:
          - not_null

exposures:
  - name: divesite_species_dashboard
    label: Divesite Species Dashboard
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/s/ipP867eyaQw
    depends_on:
      - ref('divesite_species_frequency')
      - ref('monthly_species_occurrences')
      - ref('species')
    owner:
      email: aleksandr.kolmakov@pm.me

  - name: marine_species_search
    label: Marine Species Search App
    type: application
    maturity: high
    url: https://marine-species-search.streamlit.app/
    depends_on:
      - ref('clustered_occurrences')
      - ref('species')
    owner:
      email: aleksandr.kolmakov@pm.me
