version: 2

models:
  - name: near_dive_site_occurrences
    description: >
      This model calculates the nearest dive site for each species occurrence by joining the
      `occurrences` and `divesites` tables. It ranks dive sites by their proximity to species 
      occurrences and selects the closest site for each event. The proximity is determined based 
      on a configurable distance threshold.
    columns:
      - name: dive_site
        description: >
          The title of the nearest dive site. This is retrieved from the `divesites` table.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.divesites
              field: title

      - name: event_date
        description: >
          The date of the event when the species occurrence was recorded, as inherited from the
          `occurrences` model. It is used for partitioning the ranking logic.
        data_tests:
          - not_null

      - name: species
        description: >
          The scientific name of the species observed, as inherited from the `occurrences` model.
          It ensures alignment with the WoRMS reference table.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.worms_table
              field: scientificName

      - name: individual_count
        description: >
          The count of individuals observed during the event, inherited from the `occurrences` model.
          This is used for aggregations and analysis.
        data_tests:
          - not_null

      - name: distance_to_dive_site
        description: >
          The calculated distance between the species occurrence's geographic location and
          the nearest dive site. Measured in meters, it is used to determine proximity.
        data_tests:
          - not_null

      - name: geography
        description: >
          The geographic location of the species occurrence, inherited from the `occurrences` model.
          This is used for spatial calculations and proximity ranking.
        data_tests:
          - not_null

      - name: source
        description: >
          The source of the observation data, either 'GBIF' or 'OBIS', inherited from the `occurrences` model.
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 'GBIF'
                - 'OBIS'

      - name: proximity_rank
        description: >
          The rank of the dive site based on proximity to the species occurrence. This model filters 
          for only the closest dive site, where the proximity rank equals 1.
        data_tests:
          - not_null

  - name: monthly_species_occurrences
    description: >
      This model aggregates species sightings near dive sites on a monthly basis. It combines data
      from the `near_divesite_occurrences` and `divesites` tables to count occurrences of species
      at specific dive sites and includes geographic and temporal information.
    columns:
      - name: dive_site
        description: >
          The title of the dive site where the species was sighted. This is retrieved from the 
          `near_divesite_occurrences` model and joined with the `divesites` table for additional metadata.
        data_tests:
          - not_null

      - name: species
        description: >
          The scientific name of the species observed near the dive site. This is inherited from 
          the `near_divesite_occurrences` model and used for aggregations.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.worms_table
              field: scientificName

      - name: geography
        description: >
          The geographic coordinates of the dive site, retrieved from the `divesites` table. 
          This field provides spatial context for species sightings.
        data_tests:
          - not_null

      - name: month
        description: >
          The month when the species sighting occurred, formatted as a three-letter abbreviation 
          (e.g., Jan, Feb). This is derived from the `event_date` field for temporal aggregation.
        data_tests:
          - not_null
          - accepted_values:
              values:
                - Jan
                - Feb
                - Mar
                - Apr
                - May
                - Jun
                - Jul
                - Aug
                - Sep
                - Oct
                - Nov
                - Dec

      - name: event_date
        description: >
          The exact date of the species sighting, as inherited from the `near_divesite_occurrences` model.
        data_tests:
          - not_null

      - name: sighting_count
        description: >
          The count of sightings for a specific species at a dive site on a given date. This is aggregated 
          from the `near_divesite_occurrences` model.
        data_tests:
          - not_null

  - name: divesite_species_frequency
    description: >
      This model calculates the frequency of species sightings at each dive site and ranks them 
      in descending order by their sighting count. It leverages the `near_divesite_occurrences` model 
      for input data and provides ranked insights into species activity per dive site.
    columns:
      - name: dive_site
        description: >
          The title of the dive site where species sightings occurred. This is inherited from 
          the `near_divesite_occurrences` model and used as the partitioning key for ranking.
        data_tests:
          - not_null

      - name: species
        description: >
          The scientific name of the species observed at the dive site. This field is inherited 
          from the `near_divesite_occurrences` model and used for aggregation and ranking.
        data_tests:
          - not_null
          - relationships:
              to: marine_data.worms_table
              field: scientificName

      - name: sighting_count
        description: >
          The total number of sightings for a specific species at a dive site, aggregated from 
          the `near_divesite_occurrences` model.
        data_tests:
          - not_null

      - name: frequency_rank
        description: >
          The rank of the species at a dive site based on the sighting frequency, where 1 
          indicates the most frequently sighted species. Calculated using the RANK() window function.
        data_tests:
          - not_null


exposures:

  - name: divesite_species_dashboard
    label: Divesite Species Dashboard
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/s/ipP867eyaQw


    depends_on:
      - ref('divesite_species_frequency')
      - ref('monthly_species_occurrences')
      - ref('species')

    owner:
      email: aleksandr.kolmakov@pm.me

  - name: marine_species_search
    label: Marine Species Search App
    type: application
    maturity: high
    url: https://marine-species-search.streamlit.app/


    depends_on:
      - ref('clustered_occurrences')
      - ref('species')

    owner:
      email: aleksandr.kolmakov@pm.me