marine_species_data:
  target: local
  outputs:
    local:
      type: bigquery
      method: service-account
      project: gbif-412615
      dataset: marine_data
      threads: 4 # Must be a value of 1 or greater
      keyfile: ../../secret.json
      location: US
      max_bytes_billed: 1000000
    mage:
      type: bigquery
      method: service-account
      project: gbif-412615
      dataset: marine_data
      threads: 4 # Must be a value of 1 or greater
      keyfile: /home/src/secret.json
      location: US
      max_bytes_billed: 1000000