version: 2

models:
  - name: gbif_occurrences
    description: >
      Staged view over the GBIF (Global Biodiversity Information Facility) BigQuery public dataset.
      Selects species, individual count, event date, and geography. Filters out rows missing
      coordinates, dates, or species. In dev mode, uses TABLESAMPLE SYSTEM (0.01%) to minimise
      bytes scanned.
    columns:
      - name: species
        description: Scientific name of the observed species.
        data_tests:
          - not_null

      - name: individualcount
        description: Number of individuals observed (defaults to 1 when null in source).
        data_tests:
          - not_null

      - name: eventdate
        description: Timestamp of the observation event.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry derived from decimal longitude/latitude via ST_GEOGPOINT.
        data_tests:
          - not_null

  - name: obis_occurrences
    description: >
      Staged view over the OBIS (Ocean Biogeographic Information System) GCS parquet file.
      Uses SAFE_CAST for type safety. In dev mode, applies a deterministic 1% hash-based
      sample on species (FARM_FINGERPRINT) to avoid full table scans.
    columns:
      - name: species
        description: Scientific name of the observed species.
        data_tests:
          - not_null

      - name: individualcount
        description: Number of individuals observed (defaults to 1 when null in source).
        data_tests:
          - not_null

      - name: eventdate
        description: Timestamp of the observation event, cast from source string.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry derived from decimal longitude/latitude via ST_GEOGPOINT.
        data_tests:
          - not_null

  - name: divesites
    description: >
      Materialized table of dive site locations sourced from the PADI dive-guide GCS parquet.
      Clustered by geography for efficient spatial joins downstream.
    columns:
      - name: title
        description: Human-readable name of the dive site. Not unique — different sites worldwide may share names.
        data_tests:
          - not_null

      - name: geography
        description: Point geometry of the dive site derived from longitude/latitude.
        data_tests:
          - not_null
