
version: 2

models:
  - name: divesites
    columns:
      - name: title
        description: The title of the dive site.
        tests:
          - not_null
      - name: geography
        description: The geographical location of the dive site.
        tests:
          - not_null

  - name: divesite_invasive_proximity
    columns:
      - name: title
        description: The title of the dive site.
        tests:
          - not_null
          - relationships:
              to: ref('divesites')
              field: title
      - name: eventdate
        description: The date of the invasive species occurrence.
        tests:
          - not_null
      - name: species
        description: The species of the invasive occurrence.
        tests:
          - not_null
      - name: individualcount
        description: The count of individuals in the invasive occurrence.
        tests:
          - not_null
      - name: distance_to_dive_site
        description: The distance from the invasive occurrence to the dive site.
        tests:
          - not_null
      - name: proximity_rank
        description: The rank of the invasive occurrence based on proximity to the dive site.
        tests:
          - not_null
      - name: geography
        description: The geographical location of the invasive occurrence.
        tests:
          - not_null

    description: |
      This model calculates the proximity of each invasive species occurrence to the nearest dive site.
      It uses the ST_Distance function to calculate the distance between the occurrence and the dive site.
      The proximity_rank is calculated by ordering the occurrences by their distance to the dive site.
      The model only includes occurrences that are within a certain distance (PROXIMITY_METERS) from a dive site and have occurred within a certain time window (AGGREGATION_WINDOW_DAYS).

  - name: divesite_redlist_proximity
    columns:
      - name: title
        description: The title of the dive site.
        tests:
          - not_null
          - relationships:
              to: ref('divesites')
              field: title
      - name: eventdate
        description: The date of the redlist species occurrence.
        tests:
          - not_null
      - name: species
        description: The species of the redlist occurrence.
        tests:
          - not_null
      - name: individualcount
        description: The count of individuals in the redlist occurrence.
        tests:
          - not_null
      - name: distance_to_dive_site
        description: The distance from the redlist occurrence to the dive site.
        tests:
          - not_null
      - name: proximity_rank
        description: The rank of the redlist occurrence based on proximity to the dive site.
        tests:
          - not_null
      - name: geography
        description: The geographical location of the redlist occurrence.
        tests:
          - not_null

    description: |
      This model calculates the proximity of each redlist species occurrence to the nearest dive site.
      It uses the ST_Distance function to calculate the distance between the occurrence and the dive site.
      The proximity_rank is calculated by ordering the occurrences by their distance to the dive site.
      The model only includes occurrences that are within a certain distance (PROXIMITY_METERS) from a dive site and have occurred within a certain time window (AGGREGATION_WINDOW_DAYS).